apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'package.json'
            dest: .
          - src: 'tsconfig.json'
            dest: .
  local:
    push: false # IMPORTANT: do not push images to ECR for local dev
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
